title: my new title
author: Hamid.HP
email: myemail@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I practice github and this is description
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
